services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    depends_on:
      - redis
    networks:
      - laravel
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - laravel
    volumes:
      - redis_data:/data

networks:
  laravel:
    driver: bridge

volumes:
  redis_data:
    driver: local 